### ISSUE TITLE
Program terminated with signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by Liudon** [mongodb/mongo-php-library#102]
backtrace

```
gdb /usr/local/php7/sbin/php-fpm /tmp/coredump-php-fpm.25892
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/php7/sbin/php-fpm...done.
[New LWP 25892]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool www                                                             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  mongoc_set_id_cmp (a_=a_@entry=0x7ffefef4a690, b_=b_@entry=0xc5731b5e333e4900) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-set.c:49
49	   if (a->id == b->id) {
(gdb) bt
#0  mongoc_set_id_cmp (a_=a_@entry=0x7ffefef4a690, b_=b_@entry=0xc5731b5e333e4900) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-set.c:49
#1  0x00007f46d2713d6c in bsearch (__compar=0x7f46d2713b20 <mongoc_set_id_cmp>, __size=16, __nmemb=<optimized out>, __base=0x7f46d30af0a0, __key=0x7ffefef4a690) at /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h:33
#2  mongoc_set_get (set=<optimized out>, id=id@entry=1) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-set.c:114
#3  0x00007f46d271c79b in mongoc_topology_description_server_by_id (description=description@entry=0x7f46d305f940, id=id@entry=1, error=error@entry=0x0) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-topology-description.c:535
#4  0x00007f46d271a9ed in mongoc_topology_server_by_id (topology=0x7f46d305f940, id=id@entry=1, error=error@entry=0x0) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-topology.c:571
#5  0x00007f46d26fde14 in mongoc_cluster_stream_for_server (cluster=cluster@entry=0x7f46d30600d8, server_id=server_id@entry=1, reconnect_ok=reconnect_ok@entry=false, error=error@entry=0x0) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-cluster.c:1407
#6  0x00007f46d26f9f8d in _mongoc_client_kill_cursor (client=0x7f46d30600c0, server_id=1, cursor_id=85316428959, db=db@entry=0x7ffefef4a940 "fitTime", collection=0x7f46d30a2348 "picList") at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-client.c:1273
#7  0x00007f46d2703db8 in _mongoc_cursor_destroy (cursor=0x7f46d30a2200) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-cursor.c:271
#8  0x00007f46d2703e8d in mongoc_cursor_destroy (cursor=0x7f46d30a2200) at /root/soft/mongodb-1.1.1/src/libmongoc/src/mongoc/mongoc-cursor.c:247
#9  0x00007f46d272d561 in php_phongo_cursor_free (cursor=0x7f46d3067b40) at /root/soft/mongodb-1.1.1/php_phongo.c:2073
#10 0x0000000000818741 in zend_objects_store_del (object=0x7f46d3067ba8) at /root/soft/php-src-php-7.0.1/Zend/zend_objects_API.c:182
#11 0x00000000007df126 in _zval_dtor_func_for_ptr (p=<optimized out>) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.c:109
#12 0x00000000007f0c07 in i_zval_ptr_dtor (zval_ptr=0x7f46d3061760) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.h:58
#13 zend_array_destroy (ht=0x7f46d308d0e0) at /root/soft/php-src-php-7.0.1/Zend/zend_hash.c:1301
#14 0x00000000007df116 in _zval_dtor_func_for_ptr (p=<optimized out>) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.c:96
#15 0x0000000000813dfc in i_zval_ptr_dtor (zval_ptr=0x7f46d3073108) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.h:58
#16 zend_object_std_dtor (object=0x7f46d30730e0) at /root/soft/php-src-php-7.0.1/Zend/zend_objects.c:69
#17 0x0000000000818741 in zend_objects_store_del (object=0x7f46d30730e0) at /root/soft/php-src-php-7.0.1/Zend/zend_objects_API.c:182
#18 0x00000000007df126 in _zval_dtor_func_for_ptr (p=<optimized out>) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.c:109
#19 0x0000000000813dfc in i_zval_ptr_dtor (zval_ptr=0x7f46d30751f8) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.h:58
#20 zend_object_std_dtor (object=0x7f46d30751c0) at /root/soft/php-src-php-7.0.1/Zend/zend_objects.c:69
#21 0x0000000000818741 in zend_objects_store_del (object=0x7f46d30751c0) at /root/soft/php-src-php-7.0.1/Zend/zend_objects_API.c:182
#22 0x00000000007df126 in _zval_dtor_func_for_ptr (p=<optimized out>) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.c:109
#23 0x00000000007d5aa4 in i_zval_ptr_dtor (zval_ptr=0x7f46d3068020) at /root/soft/php-src-php-7.0.1/Zend/zend_variables.h:58
#24 zend_cleanup_internal_class_data (ce=<optimized out>) at /root/soft/php-src-php-7.0.1/Zend/zend_opcode.c:188
#25 0x00000000007e6dc9 in zend_cleanup_internal_classes () at /root/soft/php-src-php-7.0.1/Zend/zend_API.c:2585
#26 0x00000000007d1eea in shutdown_executor () at /root/soft/php-src-php-7.0.1/Zend/zend_execute_API.c:338
#27 0x00000000007e09c7 in zend_deactivate () at /root/soft/php-src-php-7.0.1/Zend/zend.c:967
#28 0x0000000000783c01 in php_request_shutdown (dummy=dummy@entry=0x0) at /root/soft/php-src-php-7.0.1/main/main.c:1810
#29 0x00000000004400d6 in main (argc=<optimized out>, argv=<optimized out>) at /root/soft/php-src-php-7.0.1/sapi/fpm/fpm/fpm_main.c:1972
```

**Comment by Liudon** [comment]
i use the php framework "yaf"
[yaf github](https://github.com/laruence/yaf)

**Comment by Liudon** [comment]
I find the reason, the method "find" return object, not array.
please updated version as soon as possible.
