### ISSUE TITLE
MongoDuplicateKeyException E11000 duplicate key error collection

### ISSUE THREAD

**Issue by kralos** [mongodb/mongo-php-library#556]
**bug in or below `mongodb/mongodb` layer**

`test-lib-mongodb.php`
```php
#!/usr/bin/env php
<?php

// mongodb/mongodb
require __DIR__.'/vendor/autoload.php';

$client = new MongoDB\Client('mongodb://127.0.0.1');
$collection = $client->collisions->test;
$objectId = new MongoDB\BSON\ObjectId();
$collection->insertOne([
    '_id' => $objectId,
    'name' => 'mongodb/mongodb',
]);
```

`crontab`
```
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
*  *    *   *   *       /test/test-lib-mongodb.php
```
(There are 20 entries)

*wait for the next minute*

`mongo cli`
```
> use collisions
switched to db collisions
> db.test.find().count();
0
> db.test.find().count();
17
```

I have 3 emails from cron errors like this:
```
Fatal error: Uncaught MongoDB\Driver\Exception\BulkWriteException: E11000 duplicate key error collection: collisions.test index: _id_ dup key: { : ObjectId('5b3590c2cb6caa00012c2fa2') } in /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 114

MongoDB\Driver\Exception\BulkWriteException: E11000 duplicate key error collection: collisions.test index: _id_ dup key: { : ObjectId('5b3590c2cb6caa00012c2fa2') } in /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 114

Call Stack:
0.0001 389728 1. {main}() /test/test-lib-mongodb.php:0
0.1888 879936 2. MongoDB\Collection->insertOne() /test/test-lib-mongodb.php:12
0.2000 896712 3. MongoDB\Operation\InsertOne->execute() /test/vendor/mongodb/mongodb/src/Collection.php:799
0.2001 897392 4. MongoDB\Driver\Server->executeBulkWrite() /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php:114

PHP Fatal error: Uncaught MongoDB\Driver\Exception\BulkWriteException: E11000 duplicate key error collection: collisions.test index: _id_ dup key: { : ObjectId('5b3590c2cb6caa00012c2fa2') } in /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php:114
Stack trace:
#0 /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php(114): MongoDB\Driver\Server->executeBulkWrite('collisions.test', Object(MongoDB\Driver\BulkWrite), Array)
#1 /test/vendor/mongodb/mongodb/src/Collection.php(799): MongoDB\Operation\InsertOne->execute(Object(MongoDB\Driver\Server))
#2 /test/test-lib-mongodb.php(12): MongoDB\Collection->insertOne(Array)
#3 {main}
thrown in /test/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 114
```

**Comment by kralos** [comment]
I also tried this at the `ext-mongodb` layer but i cannot reproduce it.

```php
#!/usr/bin/env php
<?php

// ext-mongodb
$manager = new MongoDB\Driver\Manager('mongodb://127.0.0.1');
$bulk = new MongoDB\Driver\BulkWrite();
$objectId = new MongoDB\BSON\ObjectId();
$bulk->insert([
    '_id' => $objectId,
    'name' => 'ext-mongodb',
]);
$manager->executeBulkWrite('collisions.test', $bulk);
```

**Comment by kralos** [comment]
Actually I just got this error to happen with `ext-mongodb` Moving to their issue tracker

**Comment by kralos** [comment]
see https://github.com/mongodb/mongo-php-driver/issues/868
