### ISSUE TITLE
RuntimeException without message when sleeping >= 1s

### ISSUE THREAD

**Issue by rexxars** [mongodb/mongo-php-library#56]
| Thing             | version     |
|-------------------|-------------|
| MongoDB server    | v2.4.9      |
| mongodb extension | 1.0.0       |
| mongodb/mongodb   | 1.0.0-beta1 |

Maybe I'm doing something wrong, but this case came up in a unit test:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$manager = new MongoDB\Driver\Manager('mongodb://localhost:27017');
$collection = new MongoDB\Collection($manager, 'imbo.image');

$result = $collection->findOne(['user' => 'pub']);
sleep(1);
$result = $collection->findOne(['user' => 'pub']);
```

Result:
```
PHP Fatal error:  Uncaught exception 'MongoDB\Driver\Exception\RuntimeException' in /home/espenh/webdev/imbo2/vendor/mongodb/mongodb/src/Operation/Find.php:165
Stack trace:
#0 /home/espenh/webdev/imbo2/vendor/mongodb/mongodb/src/Operation/Find.php(165): MongoDB\Driver\Server->executeQuery('imbo.image', Object(MongoDB\Driver\Query), Object(MongoDB\Driver\ReadPreference))
#1 /home/espenh/webdev/imbo2/vendor/mongodb/mongodb/src/Operation/FindOne.php(80): MongoDB\Operation\Find->execute(Object(MongoDB\Driver\Server))
#2 /home/espenh/webdev/imbo2/vendor/mongodb/mongodb/src/Collection.php(346): MongoDB\Operation\FindOne->execute(Object(MongoDB\Driver\Server))
#3 /home/espenh/webdev/imbo2/test.php(15): MongoDB\Collection->findOne(Array)
#4 {main}
  thrown in /home/espenh/webdev/imbo2/vendor/mongodb/mongodb/src/Operation/Find.php on line 165
```

I tried to wrap the code in a try/catch, the result from `$e->getMessage()` is a blank string.

I also tried to set a whole bunch of timeouts I could find:
```php
[
    'waitQueueTimeoutMS' => 2000,
    'connectTimeoutMS' => 2000,
    'socketTimeoutMS' => 2000,
    'maxIdleTimeMS' => 2000,
    'wtimeoutMS' => 2000,
]
```

But none of these seemed to make any difference.

Any suggestions?

**Comment by bjori** [comment]
It happens when a socket hasn't been used for 1 second (or more).
I botched the return value, returning the opposite - hence resulting in exception being thrown incorrectly and without a message as nothing is actually wrong.

See: https://github.com/mongodb/mongo-php-driver/issues/132
