### ISSUE TITLE
Can't connect to Atlas

### ISSUE THREAD

**Issue by Adzik** [mongodb/mongo-php-library#697]
I'm trying to connect with Atlas but only got this one in logs

```
PHP Fatal error:  Uncaught MongoDB\\Driver\\Exception\\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [TLS handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed calling ismaster on 'cluster0-shard-00-01-4rpkw.mongodb.net:27017'] [TLS handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed calling ismaster on 'cluster0-shard-00-02-4rpkw.mongodb.net:27017'] [TLS handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify f in /var/www/html/dsdobot/vendor/mongodb/mongodb/src/functions.php:431\nStack trace:\n#0 /var/www/html/dsdobot/vendor/mongodb/mongodb/src/functions.php(431): MongoDB\\Driver\\Manager->selectServer(Object(MongoDB\\Driver\\ReadPreference))\n#1 /var/www/html/dsdobot/vendor/mongodb/mongodb/src/Collection.php(504): MongoDB\\select_server(Object(MongoDB\\Driver\\Manager), Array)\n#2 /var/www/html/dsdobot/sync.php(20): MongoDB\\Collection->drop()\n#3 {main}\n  thrown in /var/www/html/dsdobot/vendor/mongodb/mongodb/src/functions.php on line 431
```   

My IP is on whitelist, so it's not a problem. I tried to run it on Windows and works fine

* Linux Debian 10 (ARM)
* PHP 7.3
* Mongo driver 1.5.1 (i tried on 1.6 but the same error)
* Atlas cluster 4.0.13

[PHP INFO](https://pastebin.com/nVzxRUaK)

**Comment by jmikola** [comment]
Let's break apart the ConnectionTimeoutException message, which happens to originate from libmongoc. The high-level error is that the driver failed to select a suitable server for the drop operation (according to your stack trace). This is indicated by the "No suitable servers found" message. "(`serverSelectionTryOnce` set)" tells us that we're using a try-once style of server selection, which is the PHP driver default, so no surprises there.

Since failed server selection is a high-level error, libmongoc then reports the individual errors for each server in the topology that contributed to the selection error. This output is ultimately truncated because libmongoc uses a fixed-size buffer for its error messages, but we have enough data to see a pattern for each server. The common issue for each host is an SSL certificate verification issue:

> [TLS handshake failed: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed calling ismaster on 'cluster0-shard-00-01-4rpkw.mongodb.net:27017']

Looking at your `phpinfo()` output, we can see that libmongoc is compiled to use OpenSSL:

> libmongoc SSL library: OpenSSL

Note that this has nothing to do with PHP's OpenSSL extension or its configuration, since all socket communication in the PHP driver is done directly through libmongoc. Therefore, it's possible that your PHP environment has a certificate store configured for its OpenSSL extension that is not accessible to the PHP driver, which is limited to your operating system's OpenSSL configuration.

**Checking certificates with PHP's OpenSSL extension**
I think the first step would be to see if you can verify the Atlas certificate using PHP's stream API, which utilizes PHP's OpenSSL extension. That will tell us if there is any configuration difference between PHP's OpenSSL extension and the system OpenSSL library that libmongoc is using. For that, I'd direct you to the script examples I previously shared in https://github.com/mongodb/mongo-php-library/issues/313#issuecomment-267657600. If you modify that script to connect to one of your Atlas hosts (e.g. "cluster0-shard-00-01-4rpkw.mongodb.net:27017") using the `https://` scheme, we'll expect to see an error message about connecting to MongoDB using HTTP if we can make it past certificate verification. Again, this is testing PHP's OpenSSL extension -- not libmongoc -- but it's a good first step to check your environment.

Regarding your PHP OpenSSL extension, `phpinfo()` output does not show custom values for `openssl.cafile` and `openssl.capath` and only points to `/usr/lib/ssl/openssl.cnf` as a default configuration. I think it may be likely that PHP's OpenSSL extension will behave similarly to libmongoc, but the above test should confirm.

**Debug logs**
Additionally, if you can create a very basic PHP script that attempts to connect to Atlas and perform a single operation (e.g. drop, or even just a `ping` command), you can attempt to collect output via the `mongodb.debug` INI setting, as I've requested of another user in https://github.com/mongodb/mongo-php-library/issues/348#issuecomment-287828362. A small PHP script is desirable here to limit the amount of debug output generated. You will also want to ensure any sensitive information (e.g. passwords in your connection string) is redacted from those logs before sharing them.

**Comment by Adzik** [comment]
Here's my cluster 

```
array(16) {
  ["name"]=>
  string(74) "/C=US/ST=New York/L=New York/O=MongoDB, Inc./OU=Cloud SRE/CN=*.mongodb.net"
  ["subject"]=>
  array(6) {
    ["C"]=>
    string(2) "US"
    ["ST"]=>
    string(8) "New York"
    ["L"]=>
    string(8) "New York"
    ["O"]=>
    string(13) "MongoDB, Inc."
    ["OU"]=>
    string(9) "Cloud SRE"
    ["CN"]=>
    string(13) "*.mongodb.net"
  }
  ["hash"]=>
  string(8) "c56ebf79"
  ["issuer"]=>
  array(3) {
    ["C"]=>
    string(2) "US"
    ["O"]=>
    string(12) "DigiCert Inc"
    ["CN"]=>
    string(30) "DigiCert SHA2 Secure Server CA"
  }
  ["version"]=>
  int(2)
  ["serialNumber"]=>
  string(38) "18639574192117345081954476873740345950"
  ["serialNumberHex"]=>
  string(32) "0E05D9F5EC0B3B40C028B0C3EEE2625E"
  ["validFrom"]=>
  string(13) "180207000000Z"
  ["validTo"]=>
  string(13) "210211120000Z"
  ["validFrom_time_t"]=>
  int(1517961600)
  ["validTo_time_t"]=>
  int(1613044800)
  ["signatureTypeSN"]=>
  string(10) "RSA-SHA256"
  ["signatureTypeLN"]=>
  string(23) "sha256WithRSAEncryption"
  ["signatureTypeNID"]=>
  int(668)
  ["purposes"]=>
  array(9) {
    [1]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslclient"
    }
    [2]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslserver"
    }
    [3]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(11) "nssslserver"
    }
    [4]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(9) "smimesign"
    }
    [5]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(12) "smimeencrypt"
    }
    [6]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(7) "crlsign"
    }
    [7]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(true)
      [2]=>
      string(3) "any"
    }
    [8]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(10) "ocsphelper"
    }
    [9]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(13) "timestampsign"
    }
  }
  ["extensions"]=>
  array(10) {
    ["authorityKeyIdentifier"]=>
    string(66) "keyid:0F:80:61:1C:82:31:61:D5:2F:28:E7:8D:46:38:B4:2C:E1:C6:D9:E2
"
    ["subjectKeyIdentifier"]=>
    string(59) "A0:5E:6A:96:66:1B:B3:0D:01:C0:D5:95:43:83:11:8A:3C:38:2F:51"
    ["subjectAltName"]=>
    string(34) "DNS:*.mongodb.net, DNS:mongodb.net"
    ["keyUsage"]=>
    string(35) "Digital Signature, Key Encipherment"
    ["extendedKeyUsage"]=>
    string(60) "TLS Web Server Authentication, TLS Web Client Authentication"
    ["crlDistributionPoints"]=>
    string(120) "
Full Name:
  URI:http://crl3.digicert.com/ssca-sha2-g6.crl

Full Name:
  URI:http://crl4.digicert.com/ssca-sha2-g6.crl
"
    ["certificatePolicies"]=>
    string(89) "Policy: 2.16.840.1.114412.1.1
  CPS: https://www.digicert.com/CPS
Policy: 2.23.140.1.2.2
"
    ["authorityInfoAccess"]=>
    string(112) "OCSP - URI:http://ocsp.digicert.com
CA Issuers - URI:http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt
"
    ["basicConstraints"]=>
    string(8) "CA:FALSE"
    ["ct_precert_scts"]=>
    string(2326) "Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : A4:B9:09:90:B4:18:58:14:87:BB:13:A2:CC:67:70:0A:
                3C:35:98:04:F9:1B:DF:B8:E3:77:CD:0E:C8:0D:DC:10
    Timestamp : Feb  7 18:15:14.081 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:46:02:21:00:9C:B7:CD:69:27:3A:CE:5C:C8:30:5C:
                6D:ED:B3:91:50:13:34:C7:ED:EB:77:79:91:FE:73:3D:
                42:A4:13:D6:6F:02:21:00:9F:66:4D:2E:C6:08:CF:2B:
                60:4E:BD:A5:04:F2:A8:5D:65:91:8E:92:F3:A3:8E:32:
                A0:C2:80:B7:79:C5:F6:25
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : 87:75:BF:E7:59:7C:F8:8C:43:99:5F:BD:F3:6E:FF:56:
                8D:47:56:36:FF:4A:B5:60:C1:B4:EA:FF:5E:A0:83:0F
    Timestamp : Feb  7 18:15:14.296 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:44:02:20:31:48:26:D7:76:02:E6:A0:52:22:CB:47:
                33:6F:91:55:1C:C4:26:1C:DC:88:8C:D2:D2:A3:27:61:
                B2:EC:14:72:02:20:0D:0C:F9:0C:8B:DF:82:5D:5B:96:
                B4:93:AB:36:4B:48:4E:67:07:5F:B2:56:35:E3:09:00:
                D9:63:40:CD:A6:83
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : BB:D9:DF:BC:1F:8A:71:B5:93:94:23:97:AA:92:7B:47:
                38:57:95:0A:AB:52:E8:1A:90:96:64:36:8E:1E:D1:85
    Timestamp : Feb  7 18:15:14.246 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:45:02:20:67:34:5A:12:9A:9F:92:07:0C:84:7C:C5:
                38:0F:EC:04:5F:22:21:CA:FD:31:4A:9A:A3:48:E0:86:
                A8:05:4A:5E:02:21:00:9E:43:C0:94:D3:37:46:36:A8:
                14:32:5C:2C:B7:B9:6F:49:ED:1F:BB:AF:96:18:2E:E1:
                BE:6E:A0:DC:2C:2B:83
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : 6F:53:76:AC:31:F0:31:19:D8:99:00:A4:51:15:FF:77:
                15:1C:11:D9:02:C1:00:29:06:8D:B2:08:9A:37:D9:13
    Timestamp : Feb  7 18:15:14.824 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:46:02:21:00:D8:53:0C:90:44:D3:E4:E4:1F:28:BD:
                F4:A2:91:99:D3:1C:83:59:A4:15:6C:E6:F9:DB:AE:95:
                A2:89:E0:E8:02:02:21:00:D1:AA:41:BC:98:D6:42:72:
                A9:6D:CB:19:54:EC:A7:F3:F4:53:25:B1:BA:45:54:08:
                F3:45:9D:A9:74:FB:1B:AE"
  }
}
```   
here's mongodb.com
```
array(16) {
  ["name"]=>
  string(17) "/CN=*.mongodb.com"
  ["subject"]=>
  array(1) {
    ["CN"]=>
    string(13) "*.mongodb.com"
  }
  ["hash"]=>
  string(8) "25b5db5f"
  ["issuer"]=>
  array(4) {
    ["C"]=>
    string(2) "US"
    ["O"]=>
    string(6) "Amazon"
    ["OU"]=>
    string(12) "Server CA 1B"
    ["CN"]=>
    string(6) "Amazon"
  }
  ["version"]=>
  int(2)
  ["serialNumber"]=>
  string(38) "11196262090229725019049720558474204554"
  ["serialNumberHex"]=>
  string(32) "086C525729547748AFC6C25A9E6F958A"
  ["validFrom"]=>
  string(13) "190312000000Z"
  ["validTo"]=>
  string(13) "200412120000Z"
  ["validFrom_time_t"]=>
  int(1552348800)
  ["validTo_time_t"]=>
  int(1586692800)
  ["signatureTypeSN"]=>
  string(10) "RSA-SHA256"
  ["signatureTypeLN"]=>
  string(23) "sha256WithRSAEncryption"
  ["signatureTypeNID"]=>
  int(668)
  ["purposes"]=>
  array(9) {
    [1]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslclient"
    }
    [2]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslserver"
    }
    [3]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(11) "nssslserver"
    }
    [4]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(9) "smimesign"
    }
    [5]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(12) "smimeencrypt"
    }
    [6]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(7) "crlsign"
    }
    [7]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(true)
      [2]=>
      string(3) "any"
    }
    [8]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(10) "ocsphelper"
    }
    [9]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(13) "timestampsign"
    }
  }
  ["extensions"]=>
  array(10) {
    ["authorityKeyIdentifier"]=>
    string(66) "keyid:59:A4:66:06:52:A0:7B:95:92:3C:A3:94:07:27:96:74:5B:F9:3D:D0
"
    ["subjectKeyIdentifier"]=>
    string(59) "D1:76:A1:5C:86:0C:08:0E:2C:E2:50:5C:5B:1C:EB:3F:4C:B9:63:4B"
    ["subjectAltName"]=>
    string(68) "DNS:*.mongodb.com, DNS:*.corp.mongodb.com, DNS:*.support.mongodb.com"
    ["keyUsage"]=>
    string(35) "Digital Signature, Key Encipherment"
    ["extendedKeyUsage"]=>
    string(60) "TLS Web Server Authentication, TLS Web Client Authentication"
    ["crlDistributionPoints"]=>
    string(61) "
Full Name:
  URI:http://crl.sca1b.amazontrust.com/sca1b.crl
"
    ["certificatePolicies"]=>
    string(53) "Policy: 2.16.840.1.114412.1.2
Policy: 2.23.140.1.2.1
"
    ["authorityInfoAccess"]=>
    string(105) "OCSP - URI:http://ocsp.sca1b.amazontrust.com
CA Issuers - URI:http://crt.sca1b.amazontrust.com/sca1b.crt
"
    ["basicConstraints"]=>
    string(8) "CA:FALSE"
    ["ct_precert_scts"]=>
    string(1158) "Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : EE:4B:BD:B7:75:CE:60:BA:E1:42:69:1F:AB:E1:9E:66:
                A3:0F:7E:5F:B0:72:D8:83:00:C4:7B:89:7A:A8:FD:CB
    Timestamp : Mar 12 21:26:08.058 2019 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:45:02:20:55:64:E5:05:33:85:1D:4D:B2:32:4A:2C:
                1E:1E:F3:94:D1:B8:B7:E9:27:9C:85:F5:3D:53:7D:05:
                89:8C:2C:11:02:21:00:D6:FA:80:C4:0E:E9:DC:E6:0C:
                9F:FD:AF:54:22:D0:C7:36:E2:AF:5D:40:B0:49:00:F3:
                F6:54:32:C1:BD:8A:29
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : 87:75:BF:E7:59:7C:F8:8C:43:99:5F:BD:F3:6E:FF:56:
                8D:47:56:36:FF:4A:B5:60:C1:B4:EA:FF:5E:A0:83:0F
    Timestamp : Mar 12 21:26:08.377 2019 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:44:02:20:51:B3:12:DE:CE:8D:1F:75:AE:69:E8:D1:
                99:3B:12:AA:92:7C:64:2F:4A:8C:4A:93:7B:AA:04:79:
                D8:B0:7E:1E:02:20:65:8A:E5:3F:92:D5:44:F1:6A:29:
                8E:F9:D2:3B:B3:AD:F6:1A:4A:98:F4:1F:F1:8B:AD:02:
                CA:87:E1:0E:E8:89"
  }
}
int(121113)
```
[mongodebug.txt](https://github.com/mongodb/mongo-php-library/files/3903104/mongodebug.txt)

**Comment by jmikola** [comment]
The trace information in the debug log points agrees with the original exception message indicating that libmongoc failed to verify the certificate with OpenSSL.

The first paste you shared for the Atlas connection string did not include an `int(%d)` value after the certificate information. Can you share the output of `$contents` when running the script? I'm curious if it corresponds to the `"It looks like you are trying to access MongoDB over HTTP on the native driver port."` message from https://github.com/mongodb/mongo-php-library/issues/313#issuecomment-267657600.

**Comment by Adzik** [comment]
Just used wrong script, sorry!
There's correct one
```
array(16) {
  ["name"]=>
  string(74) "/C=US/ST=New York/L=New York/O=MongoDB, Inc./OU=Cloud SRE/CN=*.mongodb.net"
  ["subject"]=>
  array(6) {
    ["C"]=>
    string(2) "US"
    ["ST"]=>
    string(8) "New York"
    ["L"]=>
    string(8) "New York"
    ["O"]=>
    string(13) "MongoDB, Inc."
    ["OU"]=>
    string(9) "Cloud SRE"
    ["CN"]=>
    string(13) "*.mongodb.net"
  }
  ["hash"]=>
  string(8) "c56ebf79"
  ["issuer"]=>
  array(3) {
    ["C"]=>
    string(2) "US"
    ["O"]=>
    string(12) "DigiCert Inc"
    ["CN"]=>
    string(30) "DigiCert SHA2 Secure Server CA"
  }
  ["version"]=>
  int(2)
  ["serialNumber"]=>
  string(38) "18639574192117345081954476873740345950"
  ["serialNumberHex"]=>
  string(32) "0E05D9F5EC0B3B40C028B0C3EEE2625E"
  ["validFrom"]=>
  string(13) "180207000000Z"
  ["validTo"]=>
  string(13) "210211120000Z"
  ["validFrom_time_t"]=>
  int(1517961600)
  ["validTo_time_t"]=>
  int(1613044800)
  ["signatureTypeSN"]=>
  string(10) "RSA-SHA256"
  ["signatureTypeLN"]=>
  string(23) "sha256WithRSAEncryption"
  ["signatureTypeNID"]=>
  int(668)
  ["purposes"]=>
  array(9) {
    [1]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslclient"
    }
    [2]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(9) "sslserver"
    }
    [3]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(11) "nssslserver"
    }
    [4]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(9) "smimesign"
    }
    [5]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(12) "smimeencrypt"
    }
    [6]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(7) "crlsign"
    }
    [7]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(true)
      [2]=>
      string(3) "any"
    }
    [8]=>
    array(3) {
      [0]=>
      bool(true)
      [1]=>
      bool(false)
      [2]=>
      string(10) "ocsphelper"
    }
    [9]=>
    array(3) {
      [0]=>
      bool(false)
      [1]=>
      bool(false)
      [2]=>
      string(13) "timestampsign"
    }
  }
  ["extensions"]=>
  array(10) {
    ["authorityKeyIdentifier"]=>
    string(66) "keyid:0F:80:61:1C:82:31:61:D5:2F:28:E7:8D:46:38:B4:2C:E1:C6:D9:E2
"
    ["subjectKeyIdentifier"]=>
    string(59) "A0:5E:6A:96:66:1B:B3:0D:01:C0:D5:95:43:83:11:8A:3C:38:2F:51"
    ["subjectAltName"]=>
    string(34) "DNS:*.mongodb.net, DNS:mongodb.net"
    ["keyUsage"]=>
    string(35) "Digital Signature, Key Encipherment"
    ["extendedKeyUsage"]=>
    string(60) "TLS Web Server Authentication, TLS Web Client Authentication"
    ["crlDistributionPoints"]=>
    string(120) "
Full Name:
  URI:http://crl3.digicert.com/ssca-sha2-g6.crl

Full Name:
  URI:http://crl4.digicert.com/ssca-sha2-g6.crl
"
    ["certificatePolicies"]=>
    string(89) "Policy: 2.16.840.1.114412.1.1
  CPS: https://www.digicert.com/CPS
Policy: 2.23.140.1.2.2
"
    ["authorityInfoAccess"]=>
    string(112) "OCSP - URI:http://ocsp.digicert.com
CA Issuers - URI:http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt
"
    ["basicConstraints"]=>
    string(8) "CA:FALSE"
    ["ct_precert_scts"]=>
    string(2326) "Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : A4:B9:09:90:B4:18:58:14:87:BB:13:A2:CC:67:70:0A:
                3C:35:98:04:F9:1B:DF:B8:E3:77:CD:0E:C8:0D:DC:10
    Timestamp : Feb  7 18:15:14.081 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:46:02:21:00:9C:B7:CD:69:27:3A:CE:5C:C8:30:5C:
                6D:ED:B3:91:50:13:34:C7:ED:EB:77:79:91:FE:73:3D:
                42:A4:13:D6:6F:02:21:00:9F:66:4D:2E:C6:08:CF:2B:
                60:4E:BD:A5:04:F2:A8:5D:65:91:8E:92:F3:A3:8E:32:
                A0:C2:80:B7:79:C5:F6:25
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : 87:75:BF:E7:59:7C:F8:8C:43:99:5F:BD:F3:6E:FF:56:
                8D:47:56:36:FF:4A:B5:60:C1:B4:EA:FF:5E:A0:83:0F
    Timestamp : Feb  7 18:15:14.296 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:44:02:20:31:48:26:D7:76:02:E6:A0:52:22:CB:47:
                33:6F:91:55:1C:C4:26:1C:DC:88:8C:D2:D2:A3:27:61:
                B2:EC:14:72:02:20:0D:0C:F9:0C:8B:DF:82:5D:5B:96:
                B4:93:AB:36:4B:48:4E:67:07:5F:B2:56:35:E3:09:00:
                D9:63:40:CD:A6:83
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : BB:D9:DF:BC:1F:8A:71:B5:93:94:23:97:AA:92:7B:47:
                38:57:95:0A:AB:52:E8:1A:90:96:64:36:8E:1E:D1:85
    Timestamp : Feb  7 18:15:14.246 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:45:02:20:67:34:5A:12:9A:9F:92:07:0C:84:7C:C5:
                38:0F:EC:04:5F:22:21:CA:FD:31:4A:9A:A3:48:E0:86:
                A8:05:4A:5E:02:21:00:9E:43:C0:94:D3:37:46:36:A8:
                14:32:5C:2C:B7:B9:6F:49:ED:1F:BB:AF:96:18:2E:E1:
                BE:6E:A0:DC:2C:2B:83
Signed Certificate Timestamp:
    Version   : v1 (0x0)
    Log ID    : 6F:53:76:AC:31:F0:31:19:D8:99:00:A4:51:15:FF:77:
                15:1C:11:D9:02:C1:00:29:06:8D:B2:08:9A:37:D9:13
    Timestamp : Feb  7 18:15:14.824 2018 GMT
    Extensions: none
    Signature : ecdsa-with-SHA256
                30:46:02:21:00:D8:53:0C:90:44:D3:E4:E4:1F:28:BD:
                F4:A2:91:99:D3:1C:83:59:A4:15:6C:E6:F9:DB:AE:95:
                A2:89:E0:E8:02:02:21:00:D1:AA:41:BC:98:D6:42:72:
                A9:6D:CB:19:54:EC:A7:F3:F4:53:25:B1:BA:45:54:08:
                F3:45:9D:A9:74:FB:1B:AE"
  }
}
int(0)
```
It's looks like a problem with PHP, not MongoDriver because i can't get output of ```$contents```. Just got this one in error.log ```PHP Warning:  file_get_contents(https://cluster0-shard-00-01-4rpkw.mongodb.net:27017/): failed to open stream: HTTP request failed!```

**Comment by jmikola** [comment]
@Adzik: Are you using a shared Atlas instance by any chance? I just ran the script myself using two separate hosts from the replica seed list (i.e. _not_ a `mongodb+srv` URI) and noticed that the M0 cluster resulted in a "failed to open stream: HTTP request failed!" error; however, the host belonging to an M10 cluster did come back with the expected response: "It looks like you are trying to access MongoDB over HTTP on the native driver port."

If you are using a shared Atlas instance, I don't think the test script will be helpful. I would attribute this to the fact that the shared clusters run a custom server and do not have the logic to display a helpful error message when detecting an HTTP request (as exists in `mongod` and presumably `mongos`).

If, however, you're running a dedicated cluster (M10+), then I'm a bit confused as to how you encountered the "failed to open stream: HTTP request failed" error -- unless the client/driver host is being rejected by the cluster's network whitelist.

----

According to the certificate info above, the cert is signed by the "DigiCert SHA2 Secure Server CA" intermediary and should be valid based on the `validFrom` and `validTo` timestamps. In lieu of disabling certificate validation in the driver (which is not at all recommended), I think you will need to investigate how your system OpenSSL library differs from PHP. If you have access to [Atlas Support](https://docs.atlas.mongodb.com/support/), perhaps they can assist you with capturing the certificate file from your cluster and trying to [verify it manually using the `openssl` CLI binary](https://unix.stackexchange.com/q/16226/61042).

An alternative workaround would be to download the particular intermediary's CA file from https://www.digicert.com/digicert-root-certificates.htm and specify the path to that file as the `tlsCAFile` URI option in either your `MongoDB\Driver\Manager` or `MongoDB\Client` constructor. This option is documented in https://www.php.net/manual/en/mongodb-driver-manager.construct.php, along with some deprecated options for specifying a custom CA file for older versions of the extension.

**Comment by jmikola** [comment]
Closing due to inactivity. Feel free to follow-up with answers to my previous questions if this is still outstanding and we can re-open.
